### ISSUE TITLE
breaking spec with master related to recent changes in pipeline

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-input-log4j#27]
breaking spec with master related to recent changes in pipeline. Not sure if related to ng-pipeline @andrewvc ?

```
5) LogStash::Inputs::Log4j reading general information from a org.apache.log4j.spi.LoggingEvent creates event with general information
     Failure/Error: expect(subject["thread"]).to eq("main")

       expected: "main"
            got: "[217060]-pipeline-manager"

       (compared using ==)
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-log4j-2.0.4-java/spec/inputs/log4j_spec.rb:67:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:72:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
```

**Comment by andrewvc** [comment]
Ah, this is due to the fact that now with multiple pipelines we have a new thread name for the 'manager' thread for that pipeline (which is what's blocked waiting for inputs to terminate). I'll just update the spec :)
