### ISSUE TITLE
master branch build is currently broken

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-input-log4j#37]
https://travis-ci.org/logstash-plugins/logstash-input-log4j/builds/151618256

```
Randomized with seed 17943
.FFF..

Failures:

  1) LogStash::Inputs::Log4j reading general information from a org.apache.log4j.spi.LoggingEvent creates event with general information
     Failure/Error:
       org.apache.log4j.spi.LoggingEvent.new(
         "org.apache.log4j.Logger",
         org.apache.log4j.Logger.getLogger("org.apache.log4j.LayoutTest"),
         1426366971,
         org.apache.log4j.Level::INFO,
         "Hello, World",
         nil
       )

     ArgumentError:
       wrong number of arguments (6 for 0)
     # ./spec/inputs/log4j_spec.rb:40:in `log_obj'
     # ./spec/inputs/log4j_spec.rb:62:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'

  2) LogStash::Inputs::Log4j reading general information from a org.apache.log4j.spi.LoggingEvent creates event with stacktrace
     Failure/Error:
       org.apache.log4j.spi.LoggingEvent.new(
         "org.apache.log4j.Logger",
         org.apache.log4j.Logger.getLogger("org.apache.log4j.LayoutTest"),
         1426366971,
         org.apache.log4j.Level::INFO,
         "Hello, World",
         java.lang.IllegalStateException.new()
       )

     ArgumentError:
       wrong number of arguments (6 for 0)
     # ./spec/inputs/log4j_spec.rb:51:in `log_obj_with_stacktrace'
     # ./spec/inputs/log4j_spec.rb:82:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'

  3) LogStash::Inputs::Log4j reading general information from a org.apache.log4j.spi.LoggingEvent creates event without stacktrace
     Failure/Error:
       org.apache.log4j.spi.LoggingEvent.new(
         "org.apache.log4j.Logger",
         org.apache.log4j.Logger.getLogger("org.apache.log4j.LayoutTest"),
         1426366971,
         org.apache.log4j.Level::INFO,
         "Hello, World",
         nil
       )

     ArgumentError:
       wrong number of arguments (6 for 0)
     # ./spec/inputs/log4j_spec.rb:40:in `log_obj'
     # ./spec/inputs/log4j_spec.rb:77:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'

Finished in 1.44 seconds (files took 2.88 seconds to load)
6 examples, 3 failures

Failed examples:

rspec ./spec/inputs/log4j_spec.rb:61 # LogStash::Inputs::Log4j reading general information from a org.apache.log4j.spi.LoggingEvent creates event with general information
rspec ./spec/inputs/log4j_spec.rb:81 # LogStash::Inputs::Log4j reading general information from a org.apache.log4j.spi.LoggingEvent creates event with stacktrace
rspec ./spec/inputs/log4j_spec.rb:76 # LogStash::Inputs::Log4j reading general information from a org.apache.log4j.spi.LoggingEvent creates event without stacktrace

Randomized with seed 17943
```

**Comment by jordansissel** [comment]
Things seem ok lately. Closing.
